### PR TITLE
setting the color and brush size values

### PR DESCRIPTION
**Pull request by huzaifa1993**

### CODE REVIEW

**Comment by yusuf963** [comment]
where is  the PR check list? @huzaifa1993

**Comment by yusuf963** [comment]
also, please move any ticket you merged its PR to the done column, there are so many tickets in the doing column, please  keep it clean!!!!!

**Comment by huzaifa1993** [comment]
> where is the PR check list? @huzaifa1993 \
I followed the same steps for the PR check list but does nor work!

**Comment by yusuf963** [comment]
I'll approve the PR, however can you investigate this?

**Review by yusuf963 — APPROVED** [review]

**Pull request merged**
